### ISSUE TITLE
InsertManyTx and scheduled_at

### ISSUE THREAD

**Issue by ligustah** [riverqueue/river#502] opened 2024-08-05 15:58 UTC
Hey,

not sure if this is intentional, but when inserting jobs using `InsertManyTx` it seems that the `scheduled_at` column is set to `0001-01-01 00:00:00.000000 +00:00`. It's not a big deal, I think, but makes for somewhat awkward views in the UI:
![image](https://github.com/user-attachments/assets/e3daa55c-b684-49cc-b5af-b45d511f7b27)

I'm guessing I could explicitly set those with the InsertOpts, but thought it might be easier to have the same default behavior that I get when just inserting a single job.

**Comment by bgentry** [comment] 2024-08-05 17:10
Thanks for reporting.  This is likely a bug, the behavior should be the same here for `InsertTx` + `InsertManyTx`.

**Comment by bgentry** [comment] 2024-08-05 17:30
@ligustah actually, I'm not able to reproduce this. [I wrote a test](https://github.com/riverqueue/river/compare/bg-test-for-insert-many-tx-scheduled-at-default-value) which passes `nil` `InsertOpts` to `InsertManyTx`, and one which passes an empty `&InsertOpts{}`—both of them correctly write a default timestamp of `now()` to the database.

Do you have any code you can share to help understand how this is being used? Also, are you using the pgxv5 driver or database/sql?

**Comment by ligustah** [comment] 2024-08-05 18:28
Interesting. I'm using the database/sql driver to insert the jobs and the pgx for the workers. Let me see if I can create a minimal reproduction. Will report back.

**Comment by bgentry** [comment] 2024-08-05 20:43
@ligustah I think this is specific to database/sql and is a gap in the driver test suite. Compare the [`dbsql` implementation](https://github.com/riverqueue/river/blob/08ef6349316815d667e672d19b4fb389af464249/riverdriver/riverdatabasesql/river_database_sql_driver.go#L235-L238) to [the pgx one](https://github.com/riverqueue/river/blob/08ef6349316815d667e672d19b4fb389af464249/riverdriver/riverpgxv5/river_pgx_v5_driver.go#L226-L229).

Should be able to get a fix up later today. As a quick workaround, you can set `time.Now()` explicitly, but we'll have this fixed soon.

**Comment by bgentry** [comment] 2024-08-05 21:08
Should be fixed in #504 and the next release :v:

**Comment by ligustah** [comment] 2024-08-05 21:21
Amazing, thanks for the quick fix 🙏

**Closed** 2024-08-06 00:32 UTC
Labels: bug

**Comment by brandur** [comment] 2024-08-06 03:38
Fix released in v0.11.1.
